theme: jekyll-theme-minimal
title: Прыжки с парашютом в Киеве и Чернигове. Черниговский АСК &quot;Прогресс&quot; (тел. 067 460-17-12)
description: Прыжки с парашютом в Киеве, обучение и тандем прыжок. Черниговский парашютный клуб &quot;Прогресс&quot;
